feature: add config for return full document after update #350
alibaba/MongoShake pull request #354
Opened 2020-05-21 08:26 UTC by Raydy

add config for return full document after update

2020-05-21 08:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/MongoShake?pullRequest=354) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/MongoShake?pullRequest=354) before we can accept your contribution.<br/><hr/>**raydy.yan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/MongoShake?pullRequest=354) it.</sub>

2020-06-15 02:00 UTC, vinllen commented
@Raydy 方便加一下钉钉吗？这个功能没问题，但是代码上需要一些Polish

2020-06-16 01:52 UTC, vinllen requested changes

2020-06-16 01:52 UTC, vinllen commented on conf/collector.conf
> +mongo_watch_fulldocument=true
这里是改名为，放到`incr_sync.mongo_fetch_method`后面的位置吧，因为是增量阶段change_stream特有的，此处放全局不太合适。注释说明一下是change_stream特有的。此外，性能上也需要说明一下，这个置为true会降低性能，这是因为change stream的机制问题，置位UpdateLookup会影响性能。
`incr_sync.change_stream.watch_full_document = true`

2020-06-16 01:52 UTC, vinllen commented on src/mongoshake/collector/configure/configure.go
> +	MongoWatchFulldocument      bool     `config:"mongo_watch_fulldocument"`
同上对应修改。
此外，正常配置项还要在main/sanitize.go/checkConflict里面加一下参数校验以判断是否合法，如果用户的配置不是change_stream，则这个置为false。不过这里本身如果不是change_stream拉取，这个true/false也不影响，所以也可以不用加

2020-06-16 01:52 UTC, vinllen commented on src/mongoshake/oplog/changestram_event.go
> +func ConvertEvent2Oplog(input []byte, fulldoc bool) (*PartialLog, error) {
针对你这个，看看能不能补充1-2个单元测试，参考TestConvertEvent2Oplog函数。
此外，我觉得这里没必要传参进行，直接通过判断FullDocument字段是否出现更好一点

2020-06-16 01:52 UTC, vinllen commented on src/mongoshake/oplog/changestram_event.go
>  		*/
这里添加一个注释吧，关于置位full_document后，event的格式，加在updateDescription后面：
```
updateDescription:{
    // ...
},
full_document{ // only appear when enable "full_document"
    "_id": ObjectId("5e5384f97dc0f30426f01b79"),
    "kick" : 10,
    "plus_field" : 2
}
```

2020-06-16 01:52 UTC, vinllen commented on src/mongoshake/oplog/changestram_event.go
> +		if fulldoc {
是不是直接判断 event.FullDocument是否为nil更合适，如果不为nil就用这个FullDocument，nil就走下面else的分支？
不过得看下这里解析没有这个字段，event.FullDocument是否是nil，如果不行的话，传参处理也行吧。

2020-06-20 05:34 UTC, Raydy reviewed
已经按要求做了相应调整

2020-06-20 05:34 UTC, Raydy commented on src/mongoshake/oplog/changestram_event.go
> +func ConvertEvent2Oplog(input []byte, fulldoc bool) (*PartialLog, error) {
我观察了，返回的FullDocument用不为空。开启则显示全部字段，不开启则显示和updateDescription一样的内容

2020-06-20 05:34 UTC, Raydy commented on src/mongoshake/oplog/changestram_event.go
>  		*/
"FullDocument" : { //永不为 nil
			"fullDocument" : { <document> }, // 开启 full_document 之后，全部的field的值，否则与 updateDescription 相同
		}

2020-06-20 05:34 UTC, Raydy commented on src/mongoshake/oplog/changestram_event.go
> +		if fulldoc {
event.FullDocument永不为nil，就传参处理吧

2020-06-22 00:26 UTC, vinllen commented on src/mongoshake/collector/configure/configure.go
> +	WatchFullDocument				  bool     `config:"incr_sync.change_stream.watch_full_document"`
这里的命名格式跟别的对齐吧：IncrSyncChangeStreamWatchFullDocument

2020-06-22 09:51 UTC, Raydy commented on src/mongoshake/collector/configure/configure.go
> +	WatchFullDocument				  bool     `config:"incr_sync.change_stream.watch_full_document"`
之前用的tab键，现在已经全部调整为空格了

2020-06-24 07:36 UTC, merged

2020-06-24 07:36 UTC, vinllen commented
感谢PR